services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: flask run --host=0.0.0.0 --port=8000 --debug
    ports: ["8000:8000"]
    volumes:
      - .:/app
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_RUN_PORT=8000
      - APP_ENV=dev
