FROM python:3.12-slim
ENV PIP_NO_CACHE_DIR=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
# 開発ではコードは volume マウントするので COPY しない
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "wsgi:app"]

