services:
  web:
    # 既存の定義のままでOK。DBに繋ぐなら下を追加
    environment:
      - DATABASE_URL=postgres://app:pass@db:5432/appdb
    depends_on: [db]

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appdb
    ports: ["5432:5432"]              # WSL外からも触るなら付ける。内部だけなら外してよい
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
