"""Initial migration

Revision ID: 5f4128c3831e
Revises: 
Create Date: 2025-11-13 01:35:31.088053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4128c3831e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('categoryId'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('anonymousId', sa.String(length=64), nullable=True),
    sa.Column('displayName', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_anonymousId'), ['anonymousId'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('items',
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('aliasesJson', sa.JSON(), nullable=True),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.Column('defaultQty', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('searchEnabled', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.categoryId'], ),
    sa.PrimaryKeyConstraint('itemId'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_categoryId'), ['categoryId'], unique=False)

    op.create_table('plans',
    sa.Column('planId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('anonymousId', sa.String(length=64), nullable=True),
    sa.Column('departurePlace', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('companionsCount', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('planId')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_anonymousId'), ['anonymousId'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_userId'), ['userId'], unique=False)

    op.create_table('templates',
    sa.Column('templateId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('publicTitle', sa.String(length=255), nullable=False),
    sa.Column('shortNote', sa.Text(), nullable=True),
    sa.Column('itineraryOutlineJson', sa.JSON(), nullable=True),
    sa.Column('checklistSummaryJson', sa.JSON(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('itemsCount', sa.Integer(), nullable=True),
    sa.Column('essentialRatio', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('visibility', sa.String(length=40), nullable=False),
    sa.Column('displayVersion', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('templateId')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_userId'), ['userId'], unique=False)

    op.create_table('checklists',
    sa.Column('checklistId', sa.Integer(), nullable=False),
    sa.Column('planId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planId'], ['plans.planId'], ),
    sa.PrimaryKeyConstraint('checklistId')
    )
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklists_planId'), ['planId'], unique=False)

    op.create_table('itineraries',
    sa.Column('itineraryId', sa.Integer(), nullable=False),
    sa.Column('planId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('daysJson', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('isEditable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planId'], ['plans.planId'], ),
    sa.PrimaryKeyConstraint('itineraryId')
    )
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itineraries_planId'), ['planId'], unique=False)

    op.create_table('lodging_snapshots',
    sa.Column('lodgingSnapshotId', sa.Integer(), nullable=False),
    sa.Column('planId', sa.Integer(), nullable=False),
    sa.Column('sourceApi', sa.String(length=80), nullable=False),
    sa.Column('fetchedAt', sa.DateTime(), nullable=True),
    sa.Column('hotelId', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('priceBand', sa.String(length=40), nullable=True),
    sa.Column('imageUrl', sa.String(length=512), nullable=True),
    sa.Column('bookingUrl', sa.String(length=512), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('reviewAverage', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planId'], ['plans.planId'], ),
    sa.PrimaryKeyConstraint('lodgingSnapshotId')
    )
    with op.batch_alter_table('lodging_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lodging_snapshots_hotelId'), ['hotelId'], unique=False)
        batch_op.create_index(batch_op.f('ix_lodging_snapshots_planId'), ['planId'], unique=False)

    op.create_table('share_links',
    sa.Column('shareId', sa.Integer(), nullable=False),
    sa.Column('templateId', sa.Integer(), nullable=False),
    sa.Column('urlToken', sa.String(length=100), nullable=False),
    sa.Column('permission', sa.String(length=40), nullable=False),
    sa.Column('targetVersion', sa.Integer(), nullable=True),
    sa.Column('expiresAt', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('accessCount', sa.Integer(), nullable=False),
    sa.Column('createdById', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastAccessAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdById'], ['users.userId'], ),
    sa.ForeignKeyConstraint(['templateId'], ['templates.templateId'], ),
    sa.PrimaryKeyConstraint('shareId')
    )
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_links_createdById'), ['createdById'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_links_templateId'), ['templateId'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_links_urlToken'), ['urlToken'], unique=True)

    op.create_table('transport_snapshots',
    sa.Column('transportSnapshotId', sa.Integer(), nullable=False),
    sa.Column('planId', sa.Integer(), nullable=False),
    sa.Column('sourceApi', sa.String(length=80), nullable=False),
    sa.Column('compareLabel', sa.String(length=80), nullable=True),
    sa.Column('mode', sa.String(length=40), nullable=True),
    sa.Column('titleAndRoute', sa.Text(), nullable=True),
    sa.Column('durationMin', sa.Integer(), nullable=True),
    sa.Column('transferCount', sa.Integer(), nullable=True),
    sa.Column('fare', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('departureTime', sa.Time(), nullable=True),
    sa.Column('departureBand', sa.String(length=40), nullable=True),
    sa.Column('arrivalTime', sa.Time(), nullable=True),
    sa.Column('arrivalBand', sa.String(length=40), nullable=True),
    sa.Column('fetchedAt', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planId'], ['plans.planId'], ),
    sa.PrimaryKeyConstraint('transportSnapshotId')
    )
    with op.batch_alter_table('transport_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_snapshots_planId'), ['planId'], unique=False)

    op.create_table('checklist_items',
    sa.Column('checklistItemId', sa.Integer(), nullable=False),
    sa.Column('checklistId', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=True),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('isEssential', sa.Boolean(), nullable=False),
    sa.Column('reasonsJson', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('crowned', sa.Boolean(), nullable=False),
    sa.Column('orderNo', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.categoryId'], ),
    sa.ForeignKeyConstraint(['checklistId'], ['checklists.checklistId'], ),
    sa.ForeignKeyConstraint(['itemId'], ['items.itemId'], ),
    sa.PrimaryKeyConstraint('checklistItemId')
    )
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_items_categoryId'), ['categoryId'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_items_checklistId'), ['checklistId'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_items_itemId'), ['itemId'], unique=False)

    op.create_table('itinerary_slots',
    sa.Column('itinerarySlotId', sa.Integer(), nullable=False),
    sa.Column('itineraryId', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('slotType', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('placeName', sa.String(length=255), nullable=True),
    sa.Column('startTime', sa.Time(), nullable=True),
    sa.Column('endTime', sa.Time(), nullable=True),
    sa.Column('durationMin', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=40), nullable=True),
    sa.Column('packingNote', sa.Text(), nullable=True),
    sa.Column('orderNo', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['itineraryId'], ['itineraries.itineraryId'], ),
    sa.PrimaryKeyConstraint('itinerarySlotId')
    )
    with op.batch_alter_table('itinerary_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerary_slots_itineraryId'), ['itineraryId'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itinerary_slots_itineraryId'))

    op.drop_table('itinerary_slots')
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_items_itemId'))
        batch_op.drop_index(batch_op.f('ix_checklist_items_checklistId'))
        batch_op.drop_index(batch_op.f('ix_checklist_items_categoryId'))

    op.drop_table('checklist_items')
    with op.batch_alter_table('transport_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_snapshots_planId'))

    op.drop_table('transport_snapshots')
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_links_urlToken'))
        batch_op.drop_index(batch_op.f('ix_share_links_templateId'))
        batch_op.drop_index(batch_op.f('ix_share_links_createdById'))

    op.drop_table('share_links')
    with op.batch_alter_table('lodging_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lodging_snapshots_planId'))
        batch_op.drop_index(batch_op.f('ix_lodging_snapshots_hotelId'))

    op.drop_table('lodging_snapshots')
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itineraries_planId'))

    op.drop_table('itineraries')
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklists_planId'))

    op.drop_table('checklists')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_userId'))

    op.drop_table('templates')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_userId'))
        batch_op.drop_index(batch_op.f('ix_plans_anonymousId'))

    op.drop_table('plans')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_categoryId'))

    op.drop_table('items')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_anonymousId'))

    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
