"""initial

Revision ID: d4e9b7272ac3
Revises: 17173464e30f
Create Date: 2025-11-21 01:47:09.979192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e9b7272ac3'
down_revision = '17173464e30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_templates_plan_id'), ['plan_id'], unique=False)
        batch_op.create_foreign_key(None, 'plans', ['plan_id'], ['plan_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_templates_plan_id'))
        batch_op.drop_column('plan_id')

    # ### end Alembic commands ###
