"""initial

Revision ID: e8ef924323e6
Revises: 
Create Date: 2025-11-20 01:08:43.355901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ef924323e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anonymous_id', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_anonymous_id'), ['anonymous_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_variants_json', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('default_quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('is_searchable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_category_id'), ['category_id'], unique=False)

    op.create_table('plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anonymous_id', sa.String(length=64), nullable=True),
    sa.Column('departure', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('companion_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_anonymous_id'), ['anonymous_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_user_id'), ['user_id'], unique=False)

    op.create_table('templates',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('public_title', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('schedule_summary_json', sa.JSON(), nullable=True),
    sa.Column('checklist_summary_json', sa.JSON(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('required_ratio', sa.Float(), nullable=True),
    sa.Column('search_tags', sa.JSON(), nullable=True),
    sa.Column('publish_status', sa.String(length=40), nullable=False),
    sa.Column('display_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_user_id'), ['user_id'], unique=False)

    op.create_table('checklists',
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ),
    sa.PrimaryKeyConstraint('checklist_id')
    )
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklists_plan_id'), ['plan_id'], unique=False)

    op.create_table('schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('daily_plan_json', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.String(length=80), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_plan_id'), ['plan_id'], unique=False)

    op.create_table('shares',
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('url_token', sa.String(length=100), nullable=False),
    sa.Column('permission', sa.String(length=40), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('issuer_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issuer_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.template_id'], ),
    sa.PrimaryKeyConstraint('share_id')
    )
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shares_issuer_user_id'), ['issuer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shares_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shares_url_token'), ['url_token'], unique=True)

    op.create_table('stay_snapshots',
    sa.Column('stay_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('api_source', sa.String(length=80), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('hotel_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('price_range_text', sa.String(length=40), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('booking_url', sa.String(length=512), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('review_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ),
    sa.PrimaryKeyConstraint('stay_snapshot_id')
    )
    with op.batch_alter_table('stay_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stay_snapshots_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stay_snapshots_plan_id'), ['plan_id'], unique=False)

    op.create_table('transport_snapshots',
    sa.Column('transport_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('api_source', sa.String(length=80), nullable=False),
    sa.Column('compare_key', sa.String(length=80), nullable=True),
    sa.Column('transport_mode', sa.String(length=40), nullable=True),
    sa.Column('title_and_section', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('transfer_count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('departure_time_band', sa.String(length=40), nullable=True),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('arrival_time_band', sa.String(length=40), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ),
    sa.PrimaryKeyConstraint('transport_snapshot_id')
    )
    with op.batch_alter_table('transport_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_snapshots_plan_id'), ['plan_id'], unique=False)

    op.create_table('checklist_items',
    sa.Column('checklist_item_id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('reason_list_json', sa.JSON(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('is_crowned', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.checklist_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('checklist_item_id')
    )
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_items_checklist_id'), ['checklist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_items_item_id'), ['item_id'], unique=False)

    op.create_table('schedule_details',
    sa.Column('schedule_detail_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('slot_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('place_name', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('relative_time', sa.Integer(), nullable=True),
    sa.Column('move_mode', sa.String(length=40), nullable=True),
    sa.Column('packing_note', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.schedule_id'], ),
    sa.PrimaryKeyConstraint('schedule_detail_id')
    )
    with op.batch_alter_table('schedule_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_details_schedule_id'), ['schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_details_schedule_id'))

    op.drop_table('schedule_details')
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_items_checklist_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_items_category_id'))

    op.drop_table('checklist_items')
    with op.batch_alter_table('transport_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_snapshots_plan_id'))

    op.drop_table('transport_snapshots')
    with op.batch_alter_table('stay_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stay_snapshots_plan_id'))
        batch_op.drop_index(batch_op.f('ix_stay_snapshots_hotel_id'))

    op.drop_table('stay_snapshots')
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shares_url_token'))
        batch_op.drop_index(batch_op.f('ix_shares_template_id'))
        batch_op.drop_index(batch_op.f('ix_shares_issuer_user_id'))

    op.drop_table('shares')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_plan_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklists_plan_id'))

    op.drop_table('checklists')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_user_id'))

    op.drop_table('templates')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_plans_anonymous_id'))

    op.drop_table('plans')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_category_id'))

    op.drop_table('items')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_anonymous_id'))

    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
