"""add template save fields

Revision ID: eb09e9dc500e
Revises: 9249e0cf39c7
Create Date: 2026-01-27 02:49:00.076177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb09e9dc500e'
down_revision = '9249e0cf39c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('flag_a', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('flag_b', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('publish_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('publish_date')
        batch_op.drop_column('flag_b')
        batch_op.drop_column('flag_a')
        batch_op.drop_column('storage')

    # ### end Alembic commands ###
